server:
  port: 8005

spring:
  application:
    name: user-detail-service
  cloud:
    nacos:
      server-addr: 192.168.112.130:8840
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: UserCenter