server:
  port: 8018

spring:
  application:
    name: member-score-service
  cloud:
    nacos:
      server-addr: 192.168.112.130:8840
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: MemberCenter